### ISSUE TITLE
Definir como as informações serão passadas para a Adaptation Engine

### ISSUE THREAD

**Issue by ericbg27** [rdinizcal/bsn_ros#6]

**Comment by ericbg27** [comment]
Seguiremos a arquitetura com os dados sendo persistidos no Knowledge e armazenados separadamente para cada sensor ou iremos fazer uma cópia das informações e comunicar a Adaptation Engine diretamente com o Logger?

**Comment by rdinizcal** [comment]
Estou percebendo que aqui entre uma discussão mais técnica sobre como faremos para manipular as informações do knowledge repository. Porque por mais que talvez seja "mais fácil" criar tópicos e enviar e salvar mensagens em memória, utilizar o knowledge repository pode nos dar mais flexibilidade na manipulação dos dados da aplicação, além disso, os dados poderiam ser manipulados offline e não ficaríamos reféns de ter que testar os algoritmos de learning em execução.

Vou verificar a viabilidade de utilizar um sgbd ou ver se persistimos tudo em .txt como era feito antes.
